version: "3"

tasks:
  template:
    cmds:
      - |
        npx @openapitools/openapi-generator-cli author template \
         -g typescript-node \
         -o template
  generate:
    cmds:
      - rm -rf src/*

      - |
        npx @openapitools/openapi-generator-cli generate \
          --generator-name typescript \
          --input-spec spec/Fiken-API-2.0.0-modified.yaml \
          --output src \
          --config openapi-generator-cli.config.yaml \
          --template-dir template \

      - mv ./src/package.json package.json
      - mv ./src/tsconfig.json tsconfig.json
      - mv ./src/*.md ./doc
