version: "3"

tasks:
  generate:
    cmds:
      - | 
        npx openapi \
        --input ./spec/Fiken-API-2.0.0-modified.yaml \
        --output ./generated \
        --name FikenClient \
        --useOptions \