/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { address } from './address';
import type { attachment } from './attachment';
import type { contact } from './contact';
import type { invoiceLineResult } from './invoiceLineResult';
import type { projectResult } from './projectResult';

export type creditNoteResult = {
    /**
     * Id of credit note
     */
    readonly creditNoteId: number;
    /**
     * Unique credit note number generated by us.
     */
    readonly creditNoteNumber: number;
    /**
     * Norwegian KID number. Number from 2 to 25 digits long.
     */
    kid?: string;
    customer: contact;
    /**
     * Net amount (in creditNote currency) in cents.
     */
    net: number;
    /**
     * VAT amount (in creditNote currency) in cents.
     */
    vat: number;
    /**
     * Gross amount (= net+VAT) (in creditNote currency) in cents.
     */
    gross: number;
    /**
     * Net amount in NOK (in cents)
     */
    netInNok: number;
    /**
     * VAT amount in NOK (in cents)
     */
    vatInNok: number;
    /**
     * Gross amount in NOK (in cents)
     */
    grossInNok: number;
    /**
     * Comment/description printed above the credit note lines.
     */
    creditNoteText?: string;
    yourReference?: string;
    readonly ourReference?: string;
    /**
     * Reference if sending via EHF.
     */
    orderReference?: string;
    address: address;
    lines?: Array<invoiceLineResult>;
    /**
     * ISO 4217 currency code
     */
    currency?: string;
    /**
     * Issue date of the credit note, format yyyy-mm-dd
     */
    issueDate?: string;
    /**
     * If the credit note as been marked as settled (True) or not (False).
     */
    settled?: boolean;
    /**
     * Id of associated invoice
     */
    associatedInvoiceId?: number;
    /**
     * The UUID of the credit note draft used to create the credit note.
     * Credit notes created directly from invoices (POST / creditNotes/full and POST /creditNotes/partial)
     * will not have a draft uuid as no draft is created in this case.
     *
     */
    creditNoteDraftUuid?: string;
    creditNotePdf?: attachment;
    project?: projectResult;
};

