/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { address } from './address';
import type { attachment } from './attachment';
import type { contact } from './contact';
import type { invoiceLineResult } from './invoiceLineResult';
import type { projectResult } from './projectResult';
import type { saleResult } from './saleResult';

export type invoiceResult = {
    /**
     * Invoice Id
     */
    readonly invoiceId?: number;
    /**
     * Date that the invoice was created in Fiken, format yyyy-mm-dd.
     */
    readonly createdDate?: string;
    /**
     * Date that invoices was last modified in Fiken, format yyyy-mm-dd.
     */
    readonly lastModifiedDate?: string;
    /**
     * Unique invoice number generated by us.
     */
    invoiceNumber?: number;
    /**
     * Norwegian KID number. Number from 2 to 25 digits long.
     */
    kid?: string;
    /**
     * Issue date of the invoice, format yyyy-mm-dd
     */
    issueDate?: string;
    /**
     * Due date of the invoice, format yyyy-mm-dd
     */
    dueDate?: string;
    /**
     * Original due date of the invoice if the due date has been changed, format yyyy-mm-dd
     */
    originalDueDate?: string;
    /**
     * Net amount (in invoice currency) in cents.
     */
    net?: number;
    /**
     * VAT amount (in invoice currency) in cents.
     */
    vat?: number;
    /**
     * Gross amount (= net+VAT) (in invoice currency) in cents.
     */
    gross?: number;
    /**
     * Net amount in NOK (in cents)
     */
    netInNok?: number;
    /**
     * VAT amount in NOK (in cents)
     */
    vatInNok?: number;
    /**
     * Gross amount in NOK (in cents)
     */
    grossInNok?: number;
    /**
     * Purchase associated with Invoice is a cash purchase.
     */
    cash?: boolean;
    /**
     * Comment/description printed above the invoice lines
     */
    invoiceText?: string;
    yourReference?: string;
    ourReference?: string;
    orderReference?: string;
    /**
     * The UUID of invoice draft used to create the invoice.
     */
    invoiceDraftUuid?: string;
    address?: address;
    lines?: Array<invoiceLineResult>;
    /**
     * ISO 4217 currency code, default value is NOK
     */
    currency?: string;
    bankAccountNumber?: string;
    /**
     * If the invoice was not sent using Fiken this can be set to "true"
     */
    sentManually?: boolean;
    invoicePdf?: attachment;
    /**
     * Associated credit note Id(s)
     */
    associatedCreditNotes?: Array<number>;
    attachments?: Array<attachment>;
    customer?: contact;
    sale?: saleResult;
    project?: projectResult;
};

